services:
  app:
    container_name: travel-family
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/db  
      - /app/node_modules

volumes:
  sqlite_data: